server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smbsm?serverTimezone=UTC
      username: root
      password: 928328
#      driver-class-name: com.mysql.jdbc.Driver
#  devtools:
#    restart:
#      exclude: application.yml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

